GET http://localhost:5000/artists/

###
GET http://localhost:5000/artists/ckqv422q90000j1vlmzunf2tm

###
GET http://localhost:5000/artists/ckqv422q90000j1vlmzunf2tm/albums

###
POST http://localhost:5000/artists/
Content-Type: application/json

{
  "name":"test",
  "picture": "string"
}
###
PUT http://localhost:5000/artists/ckrjm0dl10000bvvldjkz93j8

{
  "name":"adzad",
  "picture": "strqdqzdzqqzdqzdqing"
}

###

DELETE http://localhost:5000/artists/ckrjnpkw90006b5vl0s7kfuo2

