GET http://localhost:5000/albums/

###
GET http://localhost:5000/albums/ckqvba1bx0001hvvl13mwtp49/songs




###
POST http://localhost:5000/albums/
Content-Type: application/json

{
    "picture":"string",
    "title":  "string",
    "artistId": "ckqv422q90000j1vlmzunf2tm"
}

###
