GET http://localhost:5000/albums/

###
GET http://localhost:5000/albums/ckqvfyb0f0003p8vl7wjy20e1/songs




###


POST http://localhost:5000/albums/
Content-Type: multipart/form-data

{
  "name":"stdggfdgsfgfgqggring",
  "picture": "string"
}

###
