GET http://localhost:5000/albums

###
POST http://localhost:5000/albums/
Content-Type: application/json

{
  "title": "The Best of Ed Motta",
  "artistName": "ed motta"
}

###
PUT http://localhost:5000/albums/ckribjlxd0003jvvl3wxc9g86
Content-Type: application/json

{
"picture":"test",
"title":"test"
}

###

DELETE http://localhost:5000/albums/ckrjlyix40000aevlbajyh2l6
Content-Type:   application/json