GET http://localhost:5000/users/


###


GET http://localhost:5000/users/ckquwmdss0000cb6voojym56f


###
DELETE http://localhost:5000/users/ckqurple80030wy6vnms8pviy


###
POST http://localhost:5000/users/
Content-Type: application/json

 {
  
  
    "firstName": "admizqdqzdn",
    "password": "123123123",
    "confirmPassword": "123123123",
    "lastName": "admin",
    "roles": [
      "admin"
    ],
  
    "username": "Admin"
  }


### 
GET http://localhost:5000/users/
Content-Type: application/json


{
    "username":"Jidayyyyyyyy",
    "password":"Jouillle01"
}


### 
POST http://localhost:5000/users/
Content-Type: application/json