import { Router } from "express";
import users from "../api/users/routes";
import albums from "../api/albums/routes";
import artists from "./artists/routes";
import playlists from "./playlists/routes";
import songs from "./songs/routes";
import auth from "./auth/routes";
import checkToken from "../../Middleware/checkToken";
import checkRole from "../../Middleware/checkRole";
const router = Router();
router.use("/users", checkToken, checkRole, users);
router.use("/albums", checkToken, checkRole, albums);
router.use("/artists", checkToken, checkRole, artists);
router.use("/songs", checkToken, checkRole, songs);
router.use("/playlists", checkToken, checkRole, playlists);
router.use("/auth", auth);
export default router;
