GET http://localhost:5000/playlists/ckrjm42yg0000igvlwsd9ngyd/songs

###
GET http://localhost:5000/playlists/
###

PUT http://localhost:5000/playlists/ckqwdm34u0011bsvlhqy0g2ig
Content-Type: : application/json

{
    "title":"tedstsfnsth23333",
    "description":"teqt",
    "picture":"test"
}
###

POST http://localhost:5000/playlists/
Content-Type: application/json

{
    "title":"tedqz",
    "description":"teqt",
    "picture":"test",
    "userId":"ckriwychh00001qvluhol6avk"
}

###

GET http://localhost:5000/playlists/


###

PUT http://localhost:5000/playlists/ckqwdm34u0011bsvlhqy0g2ig
Content-Type: : application/json

{
    "title":"tedstsfnsth23333",
    "description":"teqt",
    "picture":"test"
}